// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2YivAIJKRQlHQiMhxADZSKkp6Kyk47mo',
    appId: '1:140422073549:web:a98813168dcb070338ad84',
    messagingSenderId: '140422073549',
    projectId: 'flutter-demo-385f2',
    authDomain: 'flutter-demo-385f2.firebaseapp.com',
    storageBucket: 'flutter-demo-385f2.appspot.com',
    measurementId: 'G-90FLQV12FQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv2S-JoKeNtDV5r1Rcjlp5cDZidLglmAw',
    appId: '1:140422073549:android:48dc40795fd468a738ad84',
    messagingSenderId: '140422073549',
    projectId: 'flutter-demo-385f2',
    storageBucket: 'flutter-demo-385f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG4TqUcAXZgx9pMZ5VxpPV5JfT3o_Xcf8',
    appId: '1:140422073549:ios:08e2e81e5481c56338ad84',
    messagingSenderId: '140422073549',
    projectId: 'flutter-demo-385f2',
    storageBucket: 'flutter-demo-385f2.appspot.com',
    iosClientId: '140422073549-f32sg4kp9n88oc0084gttbe2pmp0acit.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG4TqUcAXZgx9pMZ5VxpPV5JfT3o_Xcf8',
    appId: '1:140422073549:ios:08e2e81e5481c56338ad84',
    messagingSenderId: '140422073549',
    projectId: 'flutter-demo-385f2',
    storageBucket: 'flutter-demo-385f2.appspot.com',
    iosClientId: '140422073549-f32sg4kp9n88oc0084gttbe2pmp0acit.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
